---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rediland/public_html/
    - /bin/cp -R /home/rediland/repositories/rediland/assets $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/forms $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/about.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/agent-single.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/agents-grid.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/blog-grid.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/blog-single.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/contact.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/index.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/property-grid.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/property-single.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/robots.txt $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/sitemap.xml $DEPLOYPATH