---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rediland/public_html/
    - /bin/cp -R /home/rediland/repositories/rediland/_site/assets $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/forms $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/index.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/contact.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/about.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/gallery.html $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/robots.txt $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/favicon-32x32.png $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/favicon-16x16.png $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/site.webmanifest $DEPLOYPATH
    - /bin/cp -R /home/rediland/repositories/rediland/_site/sitemap.xml $DEPLOYPATH
